# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-bluejay.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/bluejay


include vendor/pixeloverlays/bluejay/overlays.mk
