PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayBluejay \
    NfcOverlayCommon \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleBluejayOverlay \
    SettingsGoogleBluejayOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    UdfpsOverlay \
    PixelWifiOverlay2022_midyear \
    SettingsGoogleBluejayOverlayVendorRRO \
