# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-komodo.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/komodo


include vendor/pixeloverlays/komodo/overlays.mk
