PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleFutureFelixOverlay \
    SettingsGoogleOverlayFelix \
    SettingsGoogleFelixOverlayRRO \
    SettingsProviderOverlay \
    SfpsOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleFelixOverlayVendorRRO \
