# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-tokay.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/tokay


include vendor/pixeloverlays/tokay/overlays.mk
