# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-caiman.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/caiman


include vendor/pixeloverlays/caiman/overlays.mk
