# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-panther.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/panther


include vendor/pixeloverlays/panther/overlays.mk
