# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-gms.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/gms


include vendor/pixeloverlays/gms/overlays.mk
