PRODUCT_PACKAGES += \
    AccessibilityMenu \
    AvatarPickerPixelOverlay \
    PixelPrintServiceOverlay \
    PixelContactsProviderOverlay \
    GoogleConfigOverlay \
    GoogleWebViewOverlay \
    ManagedProvisioningPixelOverlay \
    PearlOverlay2024 \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2018 \
    PixelConfigOverlay2019 \
    PixelConfigOverlay2019Midyear \
    PixelConfigOverlay2021 \
    PixelConfigOverlayCommon \
    PixelSettingsGoogleOverlay \
    PixelSettingsProviderOverlay \
    PixelStorageManagerGoogleOverlay \
    SystemUIGXOverlay \
    PixelSystemUIGoogleOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    PixelFrameworkOverlay \
