# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-oriole.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/oriole


include vendor/pixeloverlays/oriole/overlays.mk
