# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-cheetah.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/cheetah


include vendor/pixeloverlays/cheetah/overlays.mk
