PRODUCT_PACKAGES += \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceAsWebcamRaven \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    NfcOverlayRaven \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleRavenOverlay \
    SettingsGoogleRavenOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    SettingsGoogleRavenOverlayVendorRRO \
