# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-raven.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/raven


include vendor/pixeloverlays/raven/overlays.mk
