# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-lynx.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/lynx


include vendor/pixeloverlays/lynx/overlays.mk
