# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-shiba.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/shiba


include vendor/pixeloverlays/shiba/overlays.mk
