# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-husky.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/husky


include vendor/pixeloverlays/husky/overlays.mk
