# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixeloverlays/setup-makefiles-akita.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixeloverlays/akita


include vendor/pixeloverlays/akita/overlays.mk
