PRODUCT_PACKAGES += \
    AvatarPickerPixelOverlay \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    PixelDisplayService__akita__auto_generated_rro_product \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleAkitaOverlay \
    SettingsGoogleAkitaOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    PixelWifiOverlay2024_midyear \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGoogleAkitaOverlayVendorRRO \
